In [7]:
from collections import namedtuple
import requests
import json

In [ ]:
# aplication interface

In [30]:
countries= 'kenya Nigeria brazil japan china germany finland egypt ghana togo'.split()

url = f'https://restcountries.eu/rest/v2/name/{name}'

# print(url)

# empty_li= []


# def name():
#     for i in countries:
#         print(i)
#         empty_li.append(f'https://restcountries.eu/rest/v2/name/{i}')   # return exit function
        

        
        
        
        
# def name1(name):
#     return f'https://restcountries.eu/rest/v2/name/{name}'

# for i  in countries:
#     empty_li.append(name1(i))
    
    
url_comp = [f'https://restcountries.eu/rest/v2/name/{name}' for name in countries]
print(url_comp)

CPU times: user 10 µs, sys: 1 µs, total: 11 µs
Wall time: 13.8 µs
['https://restcountries.eu/rest/v2/name/kenya', 'https://restcountries.eu/rest/v2/name/Nigeria', 'https://restcountries.eu/rest/v2/name/brazil', 'https://restcountries.eu/rest/v2/name/japan', 'https://restcountries.eu/rest/v2/name/china', 'https://restcountries.eu/rest/v2/name/germany', 'https://restcountries.eu/rest/v2/name/finland', 'https://restcountries.eu/rest/v2/name/egypt', 'https://restcountries.eu/rest/v2/name/ghana', 'https://restcountries.eu/rest/v2/name/togo']


In [18]:
# print(empty_li[0])

https://restcountries.eu/rest/v2/name/kenya


In [50]:
def get_country_info(url):
    response = requests.get(url)
    country = json.loads(response.text)[0]
    name, population,region = country['name'], country['population'], country['region']
    country_name = namedtuple('country_name', 'name population region')
    return country_name(name, population, region)._asdict()


get_country_info(url)

{'name': 'Togo', 'population': 7143000, 'region': 'Africa'}

In [39]:
country_list = []

for url in url_comp: 
    country_list.append(get_country_info(url))

In [51]:
new_country_list = list(map(get_country_info,url_comp))
print(new_country_list)

[{'name': 'Kenya', 'population': 47251000, 'region': 'Africa'}, {'name': 'Nigeria', 'population': 186988000, 'region': 'Africa'}, {'name': 'Brazil', 'population': 206135893, 'region': 'Americas'}, {'name': 'Japan', 'population': 126960000, 'region': 'Asia'}, {'name': 'China', 'population': 1377422166, 'region': 'Asia'}, {'name': 'Germany', 'population': 81770900, 'region': 'Europe'}, {'name': 'Finland', 'population': 5491817, 'region': 'Europe'}, {'name': 'Egypt', 'population': 91290000, 'region': 'Africa'}, {'name': 'Ghana', 'population': 27670174, 'region': 'Africa'}, {'name': 'Togo', 'population': 7143000, 'region': 'Africa'}]


In [47]:
with open('countries.csv','a') as write:
    write.writelines(str(country_list))

In [48]:
with open('countries.csv','r') as file:
    print(file.read())

[{'name': 'Kenya', 'population': 47251000, 'region': 'Africa'}, {'name': 'Nigeria', 'population': 186988000, 'region': 'Africa'}, {'name': 'Brazil', 'population': 206135893, 'region': 'Americas'}, {'name': 'Japan', 'population': 126960000, 'region': 'Asia'}, {'name': 'China', 'population': 1377422166, 'region': 'Asia'}, {'name': 'Germany', 'population': 81770900, 'region': 'Europe'}, {'name': 'Finland', 'population': 5491817, 'region': 'Europe'}, {'name': 'Egypt', 'population': 91290000, 'region': 'Africa'}, {'name': 'Ghana', 'population': 27670174, 'region': 'Africa'}, {'name': 'Togo', 'population': 7143000, 'region': 'Africa'}]


In [52]:
!pip install numpy

In [53]:
import numpy as np

In [59]:
# efficency
# mathematical operations

# it can only one data type in it. # List

np.array(['yes',1,2,3,4]).astype('object')  # represnts strings

array(['yes', '1', '2', '3', '4'], dtype=object)

In [67]:
# method function and attribute

# name()  #<--- function

# Name()  #<-- class object

# name.surname() #<--- method

# name.surname #<--- attribute


class Person:
    surname = 'ade'
    
    @property  #property converts to attibute of a class
    def email(self):
        print('ade@email.com')


In [66]:
name = Person()  #instace

name.email  #method
name.surname

ade@email.com


'ade'

In [71]:
array = np.ones(10, dtype='int')
print(array)

[1 1 1 1 1 1 1 1 1 1]


In [72]:
array.shape

(10,)

In [73]:
array.ndim

1

In [90]:
array1 = np.random.rand(2,6)
array1.shape

(2, 6)

In [106]:
# chain operations

value = ' th,e q,uick b,rown fox jumps ov,er the lazy dog'

# upper
# remove commas
# list


# # Dry
# value = value.upper()
# value = value.replace(',','')
# value = value.split()
# print(value)

# def string_convert(string):
#     return string.upper().replace(',','').split()


#chaining or piping
value = (value.upper()
        .replace(',','')
          .split()
            )


print(value)

['THE', 'QUICK', 'BROWN', 'FOX', 'JUMPS', 'OVER', 'THE', 'LAZY', 'DOG']


In [88]:
from pprint import pprint
# pprint(array1, width=30,depth=1)

trans_array = array1.T

In [89]:
trans_array.shape

(6, 2)

In [95]:
another_tran= array1.reshape((6, 2))
pprint(trans_array)

array([[0.53769499, 0.35865619],
       [0.80416203, 0.62673156],
       [0.06881327, 0.50830097],
       [0.90935584, 0.13104672],
       [0.44391791, 0.52630848],
       [0.90651259, 0.76575921]])


In [97]:
trans_array[:,1]  #what value or type are returned 

array([0.35865619, 0.62673156, 0.50830097, 0.13104672, 0.52630848,
       0.76575921])

In [112]:
qty_sold = [2,3,4,2,3,4,5,6,3]
price = [20,20,12,2,32,34,21,22]
sales = []
for qty,pri in zip(qty_sold,price):
    sales.append(qty *pri)

print(sales)

[40, 60, 48, 4, 96, 136, 105, 132]


In [118]:
arr = np.array([qty_sold,price)
print(arr)

[list([2, 3, 4, 2, 3, 4, 5, 6, 3]) list([20, 20, 12, 2, 32, 34, 21, 22])]


/Users/de_tai/opt/anaconda3/lib/python3.8/site-packages/numpy/core/_asarray.py:102: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return array(a, dtype, copy=False, order=order)


In [157]:
qty_sold = np.array([2,3,4,2,3,4,5,6])
price = np.array([20,20,12,2,32,34,21,22])

arr1 = np.array(qty_sold)
arr2= np.array(price)

In [158]:
new_arr = qty_sold* price
print(new_arr)


total_sale = new_arr.sum()

[ 40  60  48   4  96 136 105 132]


In [138]:
new_arr.cumsum()

array([ 40, 100, 148, 152, 248, 384, 489, 621])

In [139]:
np.unique(new_arr)  #

array([  4,  40,  48,  60,  96, 105, 132, 136])

In [160]:
print(np.any(new_arr))
print(np.all(new_arr))

True
True


In [163]:
new_arr[4]= 0

print(np.any(new_arr))
print(np.all(new_arr))

True
False


In [155]:
sub_set[3:] = [1,25,6,7,90]
qty_sold

array([2, 3, 4, 2, 3, 4, 5, 6])

array([2, 3, 4, 2, 3, 4, 5, 6])

In [168]:
all([False, False,False])

False

In [171]:
bool(0)


False

In [179]:
#  Indexing 
# list method [::]
# bool indexing

random_num = np.random.randint(17,size= 5)
print(random_num)

[ 8  0  8  3 15]


In [190]:
names = ['sam','bob','philip','andy','samuel']
list_names= np.array(names)
print(list_names)
list_names == 'andy'
list_names[list_names == 'andy']

['sam' 'bob' 'philip' 'andy' 'samuel']


array(['andy'], dtype='<U6')

In [191]:
list_names[list_names != 'andy']

array(['sam', 'bob', 'philip', 'samuel'], dtype='<U6')

In [192]:
random_num[list_names != 'andy']

array([ 8,  0,  8, 15])

In [193]:
# np select and where


large = np.random.randint(100,size= 20)
pprint(large)



array([30, 51, 59, 32, 14, 57, 72, 85, 43, 46, 91, 51, 88, 36, 40, 43, 25,
       80, 25, 24])


In [195]:
new = []
for val in large:
    if val %2 == 0:
        new.append(0)
    else:
        new.append(val)
print(new)

In [201]:
np.where((large % 2 ==0),0,large)

array([ 0, 51, 59,  0,  0, 57,  0, 85, 43,  0, 91, 51,  0,  0,  0, 43, 25,
        0, 25,  0])

In [205]:
condition= [large ==51, (large % 2== 0),large==85 ]
choice = [11111111111,0,85555555555]

np.select(condition,choicelist=choice, default=999999)

array([          0, 11111111111,      999999,           0,           0,
            999999,           0, 85555555555,      999999,           0,
            999999, 11111111111,           0,           0,           0,
            999999,      999999,           0,      999999,           0])

In [206]:
large

array([30, 51, 59, 32, 14, 57, 72, 85, 43, 46, 91, 51, 88, 36, 40, 43, 25,
       80, 25, 24])

In [207]:
!pip install pandas


In [208]:
import pandas as pd

In [209]:
# types Series and DataFrame

In [216]:
#  dict list, array, tuple

dict_item ={
    'a': 222,
    'b':200,
    'c':1000
}

In [218]:
dict_ser= pd.Series(dict_item)

In [224]:
lis_item=  [222,200,1000]
list_index= 'a b c'.split()
pd.Series(lis_item, index=list_index)
list_ser = pd.Series(lis_item, index= [2,1,0], dtype='float')

In [225]:
list_ser.index.name= 'sample name'

In [228]:
pd.DataFrame(list_ser, columns=['name'])

name
sample name        
2             222.0
1             200.0
0            1000.0