In [5]:
# Do not Repeat Yourself

# List
# Dict
# Set
# tuple
# variable


# 1 +1
# 2 + 2

a = 2  #variable of differet data type
print(a +a)

a= 1
b = 2
c= 'name'
d= 'a long string'

my_list = [1,2,'name','a long string']  # ordered

my_list[3]



4


'a long string'

In [11]:
long_string= [1,2,3,4,5,6,6,7,4,3,4,4,3,34,45,45,5,4,34,45,56,56,34,54]

# for i in long_string:
#     if i == 3:
#         print(long_string.index(i))
        
for indx, val in enumerate(long_string):
    if val == 3:
        print(indx)

2
9
12


In [16]:
my_dict =dict(zip(long_string,long_string))

# dictionary for duplicate keys
# helps quick searches for value

from pprint import pprint

pprint(my_dict)

my_dict.get(3)


{1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 34: 34, 45: 45, 54: 54, 56: 56}


3

In [19]:
my_set = set(long_string)
print(my_set)

{1, 2, 3, 4, 5, 6, 7, 34, 45, 54, 56}


In [77]:
from collections import deque, defaultdict, Counter, namedtuple

In [25]:
# list operation faster
#  flexibility


my_deck = deque()

my_list2 = []

print(my_deck)
print(my_list2)

deque([])
[]


In [28]:
print(dir(my_list2))
print('8' * 19)
print(dir(my_deck))

['__add__', '__class__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']
8888888888888888888
['__add__', '__bool__', '__class__', '__contains__', '__copy__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__set

In [38]:
my_list2.append(3)
my_deck.append(3)
my_deck.appendleft('i am appended left')

In [40]:
my_list2.extend(my_list)
my_deck.extend(my_list)

In [41]:
print(my_deck)
print(my_list2)

deque(['i am appended left', 'i am appended left', 1, 1, 1, 3, 1, 2, 'name', 'a long string'])
[1, 1, 1, 1, 3, 1, 2, 'name', 'a long string']


In [43]:
my_deck.rotate(-1)
print(my_deck)

deque([1, 1, 1, 3, 1, 2, 'name', 'a long string', 'i am appended left', 'i am appended left'])


In [44]:
my_list2[::-1]

['a long string', 'name', 2, 1, 3, 1, 1, 1, 1]

In [50]:
new_dict = defaultdict(int) # {key: val}
empty={}

In [65]:
for i in long_string:
    new_dict[i] += 1
    
    
# for i in long_string:
#     if i in empty:
#         print(empty.get(i))
#         empty[i]= empty.get(i)+ 1
#     else:
#         empty[i]= 1

In [63]:
print(empty)
new_dict

{1: 4, 2: 5, 3: 14, 4: 23, 5: 12, 6: 13, 7: 10, 34: 45, 45: 56, 56: 63, 54: 57}


defaultdict(int,
            {1: 4,
             2: 4,
             3: 12,
             4: 20,
             5: 8,
             6: 8,
             7: 4,
             34: 12,
             45: 12,
             56: 8,
             54: 4})

In [55]:
some= {}

some['key'] = 'this value'
print(some)

{'key': 'this value'}


In [67]:
val_counted = Counter(long_string)

In [68]:
val_counted

Counter({1: 1, 2: 1, 3: 3, 4: 5, 5: 2, 6: 2, 7: 1, 34: 3, 45: 3, 56: 2, 54: 1})

In [71]:
tup= ('ade', 1,2,3,4)
tup[0]

tup[0]= 'yes'

TypeError: 'tuple' object does not support item assignment

In [74]:
tup2 = tuple(long_string)
print(tup2)

(1, 2, 3, 4, 5, 6, 6, 7, 4, 3, 4, 4, 3, 34, 45, 45, 5, 4, 34, 45, 56, 56, 34, 54)


In [78]:
emp1 = ('ade','sam',42,'New_york', 10)
Employee = namedtuple('Employee',['firstname','lastname','age','location','salary']) #format or template

In [80]:
empl1_1 = Employee(*emp1) # Employee('ade','sam',42,'New_york', 10)

In [84]:
empl1_1.salary #change values access

10

In [93]:
class Employee2:
    def __init__(self,firstname,lastname):
        self.firstname = firstname
        self.lastname = lastname        
    def email(self):
        return f'{self.firstname}_{self.lastname}@company.com'

In [94]:
emp2 = Employee2('John', 'Doe')
emp2.email()

'John_Doe@company.com'

In [97]:
from dataclasses import dataclass

@dataclass  #<----
class Empl_3:
    
    firstname: str
    lastname: str
    age: int
    
    def email(self):
        return f'{self.firstname}_{self.lastname}@company.com'

In [99]:
empl3 = Empl_3('John', 'Doe',42)
empl3.email()
empl3.firstname

'John'

In [101]:
from typing import NamedTuple

class Empl4(NamedTuple):
    firstname: str
    lastname: str
    age: int
    
    def email(self):
        return f'{self.firstname}_{self.lastname}@company.com'


In [103]:
empl4= Empl4('John', 'Doe',42)
empl4.email()

'John_Doe@company.com'

In [104]:
pprint(empl3) # dictionary
pprint(empl4)# tuple you reassign

Empl_3(firstname='John', lastname='Doe', age=42)
Empl4(firstname='John', lastname='Doe', age=42)


##  Data Analysis

 historcal --> howfar off from initial projections  --> projections(prediction model)
 
 
 +--------
 source.                     ------> jupyter notebook ------>  report/ predcition model
 api-xml and json                   data cleaning
 database                            exploration
 csv,json hdfs, etc                  (analysis) ---> powerbi/ visualtion tool
                          

In [109]:
name = 'kenya'


url = f'https://restcountries.eu/rest/v2/name/{name}'

print(url)


https://restcountries.eu/rest/v2/name/kenya


In [110]:
!pip install requests
import requests

In [154]:
response = requests.get(url)
country = json.loads(response.text)
type(country)
country[0].get('region')
# print(country)

'Africa'

In [139]:

# pprint(country.get('name'))
# import json
# json.load(country)




In [163]:
def get_country_info(url):
    response = requests.get(url)
    country = json.loads(response.text)[0]
    name, population,region = country['name'], country['population'], country['region']
    country_name = namedtuple('country_name', 'name population region')
    return country_name(name, population, region)

In [170]:
country_name = namedtuple('country_name', 'name population region')

@dataclass
class Country_info:
    name: str
    population: int
    region: str

In [164]:
country_1 = get_country_info(url)

In [166]:
country_1.population  # namedtuple, dataclasses, dictionary

47251000

In [169]:
print(*country_1)

Kenya 47251000 Africa


In [174]:
cont= Country_info(*country_1)
cont.population

47251000

In [176]:
'kenya Nigeria brazil japan china germany finland egypt ghana togo'

# map function

a = [1,2,3,4,5]
def mul(x):
    return x *2


# for i in a:
#     print(mul(i))
    
list(map(mul,a))

2
4
6
8
10


[2, 4, 6, 8, 10]

## Numpy --> Numerical Python

In [199]:
# C extension -- pandas 

# size

!pip install numpy

In [200]:
import numpy as np

In [207]:
my_list = [x for x in range(10)]
my_arr= np.array(np.arange(10))


In [202]:
import sys
a =sys.getsizeof(my_list)
b=sys.getsizeof(my_arr)

In [203]:
a-b

59724360

In [209]:
# my_nump = np.array([1,2,3,4,5,6])

my_list
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [206]:
type(my_nump)

numpy.ndarray

In [210]:
def mul(x):
    return x *2
    
list(map(mul,my_list))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [211]:
#broadcasting
my_arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [212]:
my_arr.ndim

1

In [217]:
arr1 = [1,2,3,4,5,6]
arr2 =[7,8,9,10,11,12]

two_dim = np.array([arr1,arr2,arr2])

In [218]:
from pprint import pprint

In [219]:
pprint(two_dim)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [ 7,  8,  9, 10, 11, 12]])


In [220]:
two_dim.ndim

2

In [221]:
two_dim.shape  # row columns

(3, 6)

In [222]:
print(dir(two_dim))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift_

In [223]:
two_dim.dtype

dtype('int64')

In [224]:
two_dim[1:,1:]

array([[ 8,  9, 10, 11, 12],
       [ 8,  9, 10, 11, 12]])

In [226]:
two_dim[1:,:4]

array([[ 7,  8,  9, 10],
       [ 7,  8,  9, 10]])

In [234]:
two_dim[0,3] #[start:stop]

4

In [230]:
two_dim

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [ 7,  8,  9, 10, 11, 12]])

In [241]:
data= {'loc':233}
samp={'sam':200,'mose':90}
data.update(**samp)

In [242]:
data

{'loc': 233, 'sam': 200, 'mose': 90}